### ISSUE TITLE
"ignore colors like ..." option?

### ISSUE THREAD

**Issue by Pomax** [michaelrhodes/huey#5]
I'm trying to use huey to determine the dominant colour in ink samples written on whiteish paper, but because there's such a large white presence, huey will sometimes say that the dominant colour's actually the paper colour (due to being off white), or for black inks, it refuses to find anything because it sees only neutrals. Would it be possible to tell huey to ignore certain colour(ranges)? Like "everything that's neutral and over r/g/b 190" and/or "ignore any color r/g/b < 10" and the like?

**Comment by michaelrhodes** [comment]
I actually added an undocumented saturation-threshold option in `3.0.0` (Feb 2019) which _may_ work for your use case, but then I don’t expect those ink samples have been left waiting for 6 years… 😅

Going to close this issue, but do chime in if you’d like me to re-open!
