### ISSUE TITLE
I can't get it to work no matter what...

### ISSUE THREAD

**Issue by mahlu** [michaelrhodes/huey#7]
C:\Users\Mahlu\Desktop\example2\node_modules\get-image-data\shared.js:6
    context.drawImage(image, 0, 0)
            ^

Error: Image given has not completed loading
    at Error (native)
    at C:\Users\Mahlu\Desktop\example2\node_modules\get-image-data\shared.js:6:13
    at C:\Users\Mahlu\Desktop\example2\node_modules\get-image-data\index.js:17:34
    at load (C:\Users\Mahlu\Desktop\example2\node_modules\get-image\server.js:18:5)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)

**Comment by mahlu** [comment]
Solved by converting the image into a .png

**Comment by michaelrhodes** [comment]
Out of curiosity, what was the original file format?

**Comment by mahlu** [comment]
.jpg

I was inspired by this:
https://github.com/Automattic/node-canvas/issues/289
